/**
 * wasi:webgpu plugin exports
 *
 * @packageDocumentation
 */

export {
  // Types - Handles
  type GpuHandle,
  type GpuAdapterHandle,
  type GpuDeviceHandle,
  type GpuQueueHandle,
  type GpuBufferHandle,
  type GpuTextureHandle,
  type GpuTextureViewHandle,
  type GpuSamplerHandle,
  type GpuBindGroupLayoutHandle,
  type GpuBindGroupHandle,
  type GpuPipelineLayoutHandle,
  type GpuShaderModuleHandle,
  type GpuRenderPipelineHandle,
  type GpuComputePipelineHandle,
  type GpuCommandEncoderHandle,
  type GpuCommandBufferHandle,
  type GpuRenderPassEncoderHandle,
  type GpuComputePassEncoderHandle,
  type GpuRenderBundleHandle,
  type GpuRenderBundleEncoderHandle,
  type GpuQuerySetHandle,
  type GpuCanvasContextHandle,
  // Types - Enums
  type GpuPowerPreference,
  type GpuFeatureName,
  type GpuBufferMapState,
  type GpuTextureDimension,
  type GpuTextureViewDimension,
  type GpuTextureAspect,
  type GpuTextureFormat,
  type GpuAddressMode,
  type GpuFilterMode,
  type GpuMipmapFilterMode,
  type GpuCompareFunction,
  type GpuBufferBindingType,
  type GpuSamplerBindingType,
  type GpuTextureSampleType,
  type GpuStorageTextureAccess,
  type GpuCompilationMessageType,
  type GpuPrimitiveTopology,
  type GpuFrontFace,
  type GpuCullMode,
  type GpuBlendFactor,
  type GpuBlendOperation,
  type GpuStencilOperation,
  type GpuIndexFormat,
  type GpuVertexFormat,
  type GpuVertexStepMode,
  type GpuLoadOp,
  type GpuStoreOp,
  type GpuQueryType,
  type GpuCanvasAlphaMode,
  type GpuDeviceLostReason,
  type GpuErrorFilter,
  // Types - Descriptors
  type GpuRequestAdapterOptions,
  type GpuDeviceDescriptor,
  type GpuQueueDescriptor,
  type GpuBufferDescriptor,
  type GpuTextureDescriptor,
  type GpuTextureViewDescriptor,
  type GpuSamplerDescriptor,
  type GpuBindGroupLayoutDescriptor,
  type GpuBindGroupLayoutEntry,
  type GpuBufferBindingLayout,
  type GpuSamplerBindingLayout,
  type GpuTextureBindingLayout,
  type GpuStorageTextureBindingLayout,
  type GpuBindGroupDescriptor,
  type GpuBindGroupEntry,
  type GpuBindingResource,
  type GpuBufferBinding,
  type GpuPipelineLayoutDescriptor,
  type GpuShaderModuleDescriptor,
  type GpuShaderModuleCompilationHint,
  type GpuLayoutMode,
  type GpuProgrammableStage,
  type GpuComputePipelineDescriptor,
  type GpuRenderPipelineDescriptor,
  type GpuVertexState,
  type GpuVertexBufferLayout,
  type GpuVertexAttribute,
  type GpuPrimitiveState,
  type GpuDepthStencilState,
  type GpuStencilFaceState,
  type GpuMultisampleState,
  type GpuFragmentState,
  type GpuColorTargetState,
  type GpuBlendState,
  type GpuBlendComponent,
  type GpuCommandEncoderDescriptor,
  type GpuCommandBufferDescriptor,
  type GpuRenderPassDescriptor,
  type GpuRenderPassColorAttachment,
  type GpuRenderPassDepthStencilAttachment,
  type GpuRenderPassTimestampWrites,
  type GpuRenderPassTimestampWrite,
  type GpuComputePassDescriptor,
  type GpuComputePassTimestampWrites,
  type GpuComputePassTimestampWrite,
  type GpuRenderBundleDescriptor,
  type GpuRenderBundleEncoderDescriptor,
  type GpuQuerySetDescriptor,
  type GpuColor,
  type GpuExtent3D,
  type GpuOrigin3D,
  type GpuTexelCopyBufferInfo,
  type GpuTexelCopyTextureInfo,
  type GpuTexelCopyBufferLayout,
  type GpuCanvasConfiguration,
  type GpuCanvasToneMapping,
  type GpuCanvasConfigurationOwned,
} from './types.js'

export {
  // Interface
  WEBGPU_INTERFACE,
  // Implementations
  browserWebGPUImplementation,
  // Plugin
  webgpuPlugin,
  webgpuPlugins,
} from './plugin.js'
